language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

env:
  - DJANGO=https://github.com/django/django/zipball/master
  - DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/
  - DJANGO=django==1.4.3 --use-mirrors
  - DJANGO=django==1.3.5 --use-mirrors

install:
  - pip install $DJANGO
  - pip install django-filter==0.5.4 --use-mirrors
  - pip install six --use-mirrors
  - export PYTHONPATH=.

script:
  - python rest_framework/runtests/runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=django==1.4.3 --use-mirrors
    - python: "3.2"
      env: DJANGO=django==1.3.5 --use-mirrors
