language: python

python:
  - "2.7"
  - "3.2"

env:
  - DJANGO=https://www.djangoproject.com/download/1.5a1/tarball/
  - DJANGO=django==1.4.1 --use-mirrors
  - DJANGO=django==1.3.3 --use-mirrors

install:
  - pip install $DJANGO
  - pip install django-filter==0.5.4 --use-mirrors
  - pip install six --use-mirrors
  - export PYTHONPATH=.

script:
  - python rest_framework/runtests/runtests.py
