language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="https://www.djangoproject.com/download/1.6a1/tarball/"
  - DJANGO="django==1.5.1 --use-mirrors"
  - DJANGO="django==1.4.5 --use-mirrors"
  - DJANGO="django==1.3.7 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install coveralls
  - pip install defusedxml==0.3
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install oauth2==1.5.211 --use-mirrors; fi"
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install django-oauth-plus==2.0 --use-mirrors; fi"
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install django-oauth2-provider==0.2.4 --use-mirrors; fi"
  - "if [[ ${DJANGO::11} == 'django==1.3' ]]; then pip install django-filter==0.5.4 --use-mirrors; fi"
  - "if [[ ${DJANGO::11} != 'django==1.3' ]]; then pip install django-filter==0.6 --use-mirrors; fi"
  - export PYTHONPATH=.

script:
  - coverage run --omit="rest_framework/tests/*,rest_framework/runtests/*,rest_framework/compat.py" rest_framework/runtests/runtests.py

after_success:
  - coveralls

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.5 --use-mirrors"
    - python: "3.2"
      env: DJANGO="django==1.3.7 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.4.5 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.3.7 --use-mirrors"

