language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=https://github.com/django/django/zipball/master
  - DJANGO=django==1.4.1 --use-mirrors
  - DJANGO=django==1.3.3 --use-mirrors

install:
  - pip install $DJANGO 
  - pip install -e . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage==3.5.1 --use-mirrors

script:
  - python setup.py test
