site_name: Django REST framework
site_url: http://www.django-rest-framework.org/
site_description: Django REST framework - Web APIs for Django

repo_url: https://github.com/tomchristie/django-rest-framework

pages:
 - ['index.md', ]
 - ['tutorial/quickstart.md', ]
 - ['tutorial/1-serialization.md', 'Tutorial', '1 - Serialization']
 - ['tutorial/2-requests-and-responses.md', 'Tutorial', '2 - Requests and responses']
 - ['tutorial/3-class-based-views.md', 'Tutorial', '3 - Class based views']
 - ['tutorial/4-authentication-and-permissions.md', 'Tutorial', '4 - Authentication and permissions']
 - ['tutorial/5-relationships-and-hyperlinked-apis.md', 'Tutorial', '5 - Relationships and hyperlinked APIs']
 - ['tutorial/6-viewsets-and-routers.md', 'Tutorial', '6- Viewsets and routers']
 - ['api-guide/requests.md', 'API Guide', ]
 - ['api-guide/responses.md', 'API Guide', ]
 - ['api-guide/views.md', 'API Guide', ]
 - ['api-guide/generic-views.md', 'API Guide', ]
 - ['api-guide/viewsets.md', 'API Guide', ]
 - ['api-guide/routers.md', 'API Guide', ]
 - ['api-guide/parsers.md', 'API Guide', ]
 - ['api-guide/renderers.md', 'API Guide', ]
 - ['api-guide/serializers.md', 'API Guide', ]
 - ['api-guide/fields.md', 'API Guide', 'Serializer fields']
 - ['api-guide/relations.md', 'API Guide', 'Serializer relations']
 - ['api-guide/validators.md', 'API Guide', ]
 - ['api-guide/authentication.md', 'API Guide', ]
 - ['api-guide/permissions.md', 'API Guide', ]
 - ['api-guide/throttling.md', 'API Guide', ]
 - ['api-guide/filtering.md', 'API Guide', ]
 - ['api-guide/pagination.md', 'API Guide', ]
 - ['api-guide/content-negotiation.md', 'API Guide', ]
 - ['api-guide/format-suffixes.md', 'API Guide', ]
 - ['api-guide/reverse.md', 'API Guide', 'Returning URLs']
 - ['api-guide/exceptions.md', 'API Guide', ]
 - ['api-guide/status-codes.md', 'API Guide', ]
 - ['api-guide/testing.md', 'API Guide', ]
 - ['api-guide/settings.md', 'API Guide', ]
 - ['topics/documenting-your-api.md', 'Topics', 'Documenting your API']
 - ['topics/ajax-csrf-cors.md', 'Topics', 'AJAX, CSRF & CORS']
 - ['topics/browser-enhancements.md', 'Topics',]
 - ['topics/browsable-api.md', 'Topics', 'The Browsable API']
 - ['topics/rest-hypermedia-hateoas.md', 'Topics', 'REST, Hypermedia & HATEOAS']
 - ['topics/third-party-resources.md', 'Topics', 'Third Party Resources']
 - ['topics/contributing.md', 'Topics', 'Contributing to REST framework']
 - ['topics/rest-framework-2-announcement.md', 'Topics', '2.0 Announcement']
 - ['topics/2.2-announcement.md', 'Topics', '2.2 Announcement']
 - ['topics/2.3-announcement.md', 'Topics', '2.3 Announcement']
 - ['topics/2.4-announcement.md', 'Topics', '2.4 Announcement']
 - ['topics/kickstarter-announcement.md', 'Topics', 'Kickstarter Announcement']
 - ['topics/release-notes.md', 'Topics', 'Release Notes']
 - ['topics/credits.md', 'Topics', 'Credits']

site_dir: html
theme_dir: docs_theme
copyright: Copyright &copy; 2014, <a href='https://twitter.com/_tomchristie'>Tom Christie</a>.
google_analytics: ['UA-18852272-2', 'django-rest-framework.org']
